version: '3'

volumes:
  mongovolume:

services:
  application:
    image: docker-node-express-mongoapp
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 'yarn dev'
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - "9229:9229"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - 'mongo'

  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - mongovolume:/data/db # working - volume created in volume section
    # environment:
    # - COMPOSE_CONVERT_WINDOWS_PATHS=1
  
  adminmongo:
    image: "mrvautin/adminmongo"
    environment:
      - HOST=0.0.0.0
    ports:
      - "1234:1234"
